### ISSUE TITLE
problem running the example

### ISSUE THREAD

**Issue by ttsesm** [alievk/npbg#5] opened 2020-07-23 16:34 UTC
Hi,

I am trying to run the example code from the readme file but I am getting the following error:
```
$ python viewer.py --config downloads/person_1.yaml --viewport 2000,1328 --origin-view
loading pointcloud...
Traceback (most recent call last):
  File "viewer.py", line 434, in <module>
    my_app = MyApp(args)
  File "viewer.py", line 112, in __init__
    self.scene_data = load_scene_data(args.config)
  File "/home/ttsesm/Development/npbg/npbg/gl/utils.py", line 263, in load_scene_data
    pointcloud = import_model3d(fix_relative_path(config['pointcloud'], path))
  File "/home/ttsesm/Development/npbg/npbg/gl/utils.py", line 431, in import_model3d
    model['rgb'] = data.colors[0][:, :3] / 255.
IndexError: too many indices for array
```

 any idea what could be the cause?

**Comment by alievk** [comment] 2020-07-23 20:34
Probably this is caused by the `trimesh` version mismatch. Which version do you have?

**Comment by bobluoluo** [comment] 2020-07-26 14:20
mine is 3.7.13. It was automatically installed by the "install_deps" script. 
What's correct version I should install to evaluate this repo?

**Comment by seva100** [comment] 2020-07-26 14:32
@ttsesm @bobluoluo please try substituting a [line 431](https://github.com/alievk/npbg/blob/290cc5088f99301a3a2688c6ff1fc521819b8b42/npbg/gl/utils.py#L431) in npbg/utils/gl.py from
`model['rgb'] = data.colors[0][:, :3] / 255.`
to 
`model['rgb'] = data.colors[:, :3] / 255.`

Please tell us if this helps.

**Comment by ttsesm** [comment] 2020-07-27 07:25
On my side, I had trimesh 3.7.12 installed automatically by the "install_deps" script.

In any case applying @seva100's fix did the trick for me.

**Comment by seva100** [comment] 2020-07-27 08:10
Thanks @ttsesm! Merged.

**Closed by seva100** 2020-07-27 08:10 UTC
